package com.p5rte.Utils;

import java.nio.file.Paths;

public final class Constants {
    
    public static final class Path {
        // Folders
        public static final String SRC = "src/";
        public static final String FXML_FOLDER = "/com/p5rte/";
        
        // Table Stuff
        public static final String ROOT_DIR = Paths.get("").toAbsolutePath().toString();
        public static final String INPUT = Paths.get(ROOT_DIR, "input").toString();
        public static final String OUTPUT = Paths.get(ROOT_DIR, "output").toString();

        public static final String INPUT_PERSONA_TABLE = INPUT+"/PERSONA.TBL";
        public static final String OUTPUT_PERSONA_TABLE = OUTPUT+"/PERSONA.TBL";

        public static final String INPUT_UNIT_TABLE = INPUT+"/UNIT.TBL";
        public static final String OUTPUT_UNIT_TABLE = OUTPUT+"/UNIT.TBL";

        // FXML Paths
        public static final String MAIN_MENU = FXML_FOLDER+"MainMenu.fxml";
        public static final String PERSONA_TABPANE = FXML_FOLDER + "PersonaEditorTabPane.fxml";
        public static final String PERSONA_GENERAL = FXML_FOLDER + "PersonaEditorGeneral.fxml";
        public static final String PERSONA_SKILLS = FXML_FOLDER + "PersonaEditorSkills.fxml";
        public static final String DARK_MODE_CSS = FXML_FOLDER + "DarkMode.css";
    }


    // https://amicitia.miraheze.org/wiki/Persona_5_Royal/Personas
    // Will eventually be read from Name.TBL . Chance of that happening is near zero, suffer the curse of 464 hard-coded values
    public static final String[] personaIDtoName = new String[] {
        "0",
        "Metatron",
        "Beelzebub",
        "Cu Chulainn",
        "Jack-o'-Lantern",
        "Jack Frost",
        "Pixie",
        "Cerberus",
        "Lilim",
        "Eligor",
        "Odin",
        "Hua Po",
        "Decarabia",
        "Mara",
        "Ose",
        "Thor",
        "Unicorn",
        "Uriel",
        "Sarasvati",
        "Valkyrie",
        "Yaksini",
        "Ganesha",
        "Anubis",
        "Mot",
        "Raphael",
        "Scathach",
        "High Pixie",
        "Barong",
        "Girimehkala",
        "King Frost",
        "Narcissus",
        "Isis",
        "Lamia",
        "Legion",
        "Rakshasa",
        "Mokoi",
        "Forneus",
        "Setanta",
        "Titania",
        "Incubus",
        "Oni",
        "Lilith",
        "Rangda",
        "Makami",
        "Parvati",
        "Gabriel",
        "Zaou-Gongen",
        "Alice",
        "Kali",
        "Kurama Tengu",
        "Oberon",
        "Shiki-Ouji",
        "Yamata-no-Orochi",
        "Orobas",
        "Hanuman",
        "Archangel",
        "Obariyon",
        "Queen Mab",
        "Sandalphon",
        "Abaddon",
        "Shiisaa",
        "Sandman",
        "Belial",
        "Leanan Sidhe",
        "Cybele",
        "Chernobog",
        "Flauros",
        "Ippon-Datara",
        "Orthrus",
        "Succubus",
        "Mothman",
        "RESERVE",
        "Dominion",
        "Nekomata",
        "Black Frost",
        "Arahabaki",
        "Angel",
        "Skadi",
        "Kikuri-Hime",
        "Chi You",
        "Power",
        "Inugami",
        "Nebiros",
        "RESERVE",
        "Slime",
        "Anzu",
        "Yatagarasu",
        "Yoshitsune",
        "Take-Minakata",
        "Ame-no-Uzume",
        "Kushinada",
        "Kumbhanda",
        "Ongyo-Ki",
        "Kin-Ki",
        "Sui-Ki",
        "Fuu-Ki",
        "Jatayu",
        "Kaiwan",
        "Kelpie",
        "Thoth",
        "Dionysus",
        "Apsaras",
        "Andras",
        "RESERVE",
        "Koropokguru",
        "Koppa Tengu",
        "Regent",
        "Queen's Necklace",
        "Stone of Scone",
        "Koh-i-Noor",
        "Orlov",
        "Emperor's Amulet",
        "Hope Diamond",
        "Crystal Skull",
        "Orichalcum",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "Mandrake",
        "Baal",
        "Dakini",
        "Silky",
        "Bugs",
        "Black Ooze",
        "Bicorn",
        "Mithras",
        "Sudama",
        "Kodama",
        "Agathion",
        "Onmoraki",
        "Nue",
        "Pisaca",
        "Melchizedek",
        "Baphomet",
        "Raja Naga",
        "Naga",
        "Garuda",
        "Moloch",
        "Norn",
        "Belphegor",
        "Berith",
        "Choronzon",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "Nigi Mitama",
        "Kushi Mitama",
        "Ara Mitama",
        "Saki Mitama",
        "RESERVE",
        "Shiva",
        "Michael",
        "Asura",
        "Mada",
        "Mother Harlot",
        "Clotho",
        "Lachesis",
        "Atropos",
        "Ardha",
        "RESERVE",
        "Vishnu",
        "Hariti",
        "Yurlungur",
        "Hecatoncheires",
        "Satanael",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "Orpheus",
        "Thanatos",
        "Izanagi",
        "Magatsu-Izanagi",
        "Kaguya",
        "Ariadne",
        "Asterius",
        "Tsukiyomi",
        "Messiah",
        "Messiah Picaro",
        "Orpheus Picaro",
        "Thanatos Picaro",
        "Izanagi Picaro",
        "M. Izanagi Picaro",
        "Kaguya Picaro",
        "Ariadne Picaro",
        "Asterius Picaro",
        "Tsukiyomi Picaro",
        "Satanael",
        "Arsene (Intro)",
        "Arsene",
        "Captain Kidd",
        "Zorro",
        "Carmen",
        "Goemon",
        "Johanna",
        "Milady",
        "Necronomicon",
        "Robin Hood",
        "Loki",
        "Satanael",
        "Seiten Taisei",
        "Mercurius",
        "Hecate",
        "Kamu Susano-o",
        "Anat",
        "Astarte",
        "Prometheus",
        "Loki",
        "Arsene",
        "Captain Kidd",
        "Zorro",
        "Carmen",
        "Goemon",
        "Johanna",
        "Milady",
        "Necronomicon",
        "Robin Hood",
        "Cendrillon (Intro)",
        "Lucifer",
        "Seiten Taisei",
        "Mercurius",
        "Hecate",
        "Kamu Susano-o",
        "Anat",
        "Astarte",
        "Prometheus",
        "Loki",
        "Loki",
        "Cendrillon",
        "Vanadis",
        "William",
        "Diego",
        "Celestine",
        "Gorokichi",
        "Agnes",
        "Lucy",
        "Al Azif",
        "Hereward",
        "Ella",
        "RESERVE",
        "Satan",
        "Lucifer",
        "Kohryu",
        "Okuninushi",
        "Norn",
        "RESERVE",
        "RESERVE",
        "Futsunushi",
        "RESERVE",
        "Seth",
        "Ishtar",
        "RESERVE",
        "Surt",
        "Ex-Siegfried",
        "Lakshmi",
        "RESERVE",
        "RESERVE",
        "Ex-Belphegor",
        "RESERVE",
        "Garuda",
        "Fortuna",
        "Suzaku",
        "Seiryu",
        "Genbu",
        "Byakko",
        "Bishamonten",
        "Koumokuten",
        "Jikokuten",
        "Zouchouten",
        "Hell Biker",
        "Daisoujou",
        "Trumpeter",
        "White Rider",
        "Matador",
        "Pale Rider",
        "Horus",
        "RESERVE",
        "Attis",
        "RESERVE",
        "RESERVE",
        "Sraosha",
        "Berith",
        "RESERVE",
        "Mitra",
        "Phoenix",
        "Principality",
        "Neko Shogun",
        "Vasuki",
        "Ananta",
        "Throne",
        "RESERVE",
        "Quetzalcoatl",
        "Red Rider",
        "Black Rider",
        "RESERVE",
        "Ex-Moloch",
        "Pazuzu",
        "Cendrillon for Timing",
        "Slime",
        "Jack-o'-Lantern",
        "Agathion",
        "Mandrake",
        "Shiisaa",
        "Jack Frost",
        "Sudama",
        "Onmoraki",
        "Bugs",
        "Pixie",
        "Pixie",
        "Ardha",
        "RESERVE",
        "Asmodeus",
        "Azazel",
        "Baal",
        "Tithoes",
        "Mammon",
        "Leviathan",
        "Samael",
        "Maria",
        "Vohu Manah",
        "Cait Sith",
        "Mishaguji",
        "Frost for Challenge",
        "Angels for the Challenge",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "RESERVE",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P6 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "Izanagi-no-Okami",
        "Psyche",
        "Athena",
        "Raoul",
        "Orpheus Telos",
        "Orpheus",
        "Izanagi-no-Okami Pic.",
        "Psyche Picaro",
        "Athena Picaro",
        "Neo Arsene Picaro",
        "Orpheus Telos Picaro",
        "Orpheus Picaro",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "P5 Unused",
        "Macabre",
        "Alilat",
        "Thunderbird",
        "Fafnir",
        "Byakhee",
        "Hastur",
        "Tam Lin",
        "Throne",
        "Surt",
        "Loa",
        "Chimera",
        "Atavaka",
        "Cait Sith",
        "Siegfried",
        "P5 Unused",
        "P5 Unused",
        "Lavenza's Kelpie",
        "Lavenza's Berith",
        "Lavenza's Inugami",
        "Lavenza's Nue",
        "Lavenza's Oni",
        "Lavenza's Anubis",
        "Lavenza's Mithras",
        "Lavenza's Ose",
        "Lavenza's Atavak",
        "Lavenza's Thor",
        "Lavenza's Lucifer",
        "P3 Orpheus",
        "P4 Izanagi",
        "P3 Thanatos",
        "P3 Messiah",
        "P3 Attis",
        "P3 Siegfried",
        "P4 Koryu",
        "P4 Kaguya",
        "P4 Sraosha",
        "P4 Yoshitsune",
        "P4 Izanagi No Okami",
        "RESERVE",
        "RESERVE",
    };
}